version: '3.0'
services:
  nginx:
    container_name: nginx
    image: service_nginx
    depends_on:
      - php-fpm
    ports:
      - "80:80"
    volumes:
      - ../config/nginx:/etc/nginx/conf.d
      - ../logs/nginx:/var/log/nginx
      - "phpsocket:/var/run/php"
    restart: always

  php-fpm:
    container_name: php
    image: service_php
    volumes:
      - ../www:/usr/loacl/www
      - ../config/php/zz-php.ini:/usr/local/etc/php/php.ini
      - ../config/php/zz-php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ../logs/php:/var/log/php-fpm
      - "phpsocket:/var/run/php"
    network_mode: "host"
    restart: always

  mysql-db:
      container_name: mysql
      image: service_mysql
      ports:
        - "3306:3306"
      volumes:
        - ../data/mysql:/var/lib/mysql
        - ../logs/mysql:/var/lib/mysql-logs
        - ../config/mysql/conf.d:/etc/mysql/conf.d
      environment:
        MYSQL_ROOT_PASSWORD: 123456
      restart: always

  redis-db:
      container_name: redis
      image: service_redis
      ports:
        - "6379:6379"
      volumes:
        - ../data/redis:/data/data
        - ../logs/redis:/data/log/
        - ../config/redis:/data/etc/
      restart: always

volumes:
  phpsocket:
